# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c698be3f1ea2db181b0831e7effee61f252becaa011eab256895e8f31dc453c16d361195fc2a5678681cc00132e11dfa923acb237a0300c0fec0ef10f1b8cb51

test:
  secret_key_base: 6cbddab2c9640fb66bf3cbf46226dcc6f9e1901c767b87eea87c67fae89063cf6a0e5c1b0408e9db2f66b7cfb66351b9d3561fa825b7bba26f42944b15534429

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
